// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClqmzA3mi5DlO_AvyxT7knB_7ZKxo7ShM',
    appId: '1:1060122330535:web:59dba3db3e2996da24e282',
    messagingSenderId: '1060122330535',
    projectId: 'whatsapp-dude-fde13',
    authDomain: 'whatsapp-dude-fde13.firebaseapp.com',
    storageBucket: 'whatsapp-dude-fde13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLfHdLtEayhMMzg3hDDV3jsjsDzXgH5RQ',
    appId: '1:1060122330535:android:8a6f8dec66eb828a24e282',
    messagingSenderId: '1060122330535',
    projectId: 'whatsapp-dude-fde13',
    storageBucket: 'whatsapp-dude-fde13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3A-2inQNWE3BaLKA2amxUVCQW4Akcq68',
    appId: '1:1060122330535:ios:5dc8f967ea18805b24e282',
    messagingSenderId: '1060122330535',
    projectId: 'whatsapp-dude-fde13',
    storageBucket: 'whatsapp-dude-fde13.appspot.com',
    iosClientId: '1060122330535-t0cme1ubo24l27ifodkg40gf9eia8m19.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3A-2inQNWE3BaLKA2amxUVCQW4Akcq68',
    appId: '1:1060122330535:ios:5dc8f967ea18805b24e282',
    messagingSenderId: '1060122330535',
    projectId: 'whatsapp-dude-fde13',
    storageBucket: 'whatsapp-dude-fde13.appspot.com',
    iosClientId: '1060122330535-t0cme1ubo24l27ifodkg40gf9eia8m19.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
